// AUTO-GENERATED by tools/import-osm.mjs — do not edit by hand.
//
// This lists the real-geography region files (OSM + terrain DEM) that have been
// imported. It starts EMPTY, so a fresh checkout builds fine and falls back to
// the handcrafted maps in ../map.ts. After you run the importer (which writes a
// <id>.json next to this file), it rewrites this list to wire that JSON in, and
// buildRegions() uses it instead of the handcrafted version of that region.
import type { RegionData } from "../map";

export const IMPORTED_REGIONS: RegionData[] = [];
